name = "<app-name>"
main = "./src/worker.ts"
compatibility_date = "2024-07-18"


[[d1_databases]]
name = "<database-name>"
binding = "DATABASE"
database_id = "<database-id>"

[vars]
GITHUB_CLIENT_ID = "<github-client-id>"
GITHUB_CLIENT_SECRET = "<github-client-secret>"
